/**
 * Seed data for the Meridian Servicing Console demo.
 *
 * One logged-in advisor (Priya Nair), a small team, the department queues, and a
 * diverse worklist of mortgage-servicing cases. Two cases are the "hero" cases
 * the voice walks through:
 *   - MS-1042  Daniel Cho     — rate change (worked on screen with the advisor)
 *   - MS-1057  Eleanor Whitmore — early closure (prepared in the background)
 * The rest give the board its enterprise breadth (varied types/stages/assignees).
 */

import type { Case, Comment, Department, Person, Workspace } from './types';

export const ADVISOR: Person = {
  id: 'u-priya',
  name: 'Priya Nair',
  role: 'Senior Servicing Advisor',
  initials: 'PN',
};

export const TEAM: Person[] = [
  ADVISOR,
  { id: 'u-marcus', name: 'Marcus Bell', role: 'Servicing Advisor', initials: 'MB' },
  { id: 'u-dana', name: 'Dana Ortiz', role: 'Servicing Advisor', initials: 'DO' },
  { id: 'u-sam', name: 'Sam Whitfield', role: 'Team Lead', initials: 'SW' },
];

export const DEPARTMENTS: Department[] = [
  { id: 'pricing', label: 'Pricing' },
  { id: 'closures', label: 'Closures & Payoffs' },
  { id: 'legal', label: 'Legal & Custody' },
  { id: 'insurance', label: 'Insurance & Escrow' },
  { id: 'compliance', label: 'Compliance' },
];

function days(n: number): number {
  return n;
}

// Seed cases without the assistant-populated fields (findings/blocker/packet) or
// comments; those start empty and are filled by the desk/advisor at runtime
// (comments are merged in from SEED_COMMENTS below).
type SeedCase = Omit<Case, 'findings' | 'blocker' | 'packet' | 'comments'>;

const RAW_CASES: SeedCase[] = [
  // ── HERO 1 — Rate change, worked on screen ────────────────────────────────
  {
    id: 'c-1042',
    ref: 'MS-1042',
    type: 'rate_change',
    title: 'Rate reduction request',
    customer: {
      name: 'Daniel Cho',
      segment: 'Premier',
      loanId: 'HL-4471902',
      product: '30-yr fixed home loan',
      balance: 612400,
      rate: 7.1,
      monthlyPayment: 4120,
      property: 'San Jose, CA',
      tenureYears: 4,
      since: '2021',
    },
    stage: 'in_progress',
    priority: 'high',
    assignee: { kind: 'person', id: 'u-priya', label: 'Priya Nair' },
    openedDays: days(1),
    slaHours: 24,
    summary: 'Customer asked to lower his rate; comparing to current market and retention offers.',
    request: '“My rate feels high versus what I’m seeing advertised. Can you bring it down?”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [
      { id: 'a1', ts: 0, actor: 'system', text: 'Case created from inbound call' },
      { id: 'a2', ts: 0, actor: 'advisor', text: 'Priya Nair picked up the case' },
    ],
    payments: [
      { date: 'May 2026', amount: 4120, principal: 1480, interest: 2640, escrow: 0 },
      { date: 'Apr 2026', amount: 4120, principal: 1471, interest: 2649, escrow: 0 },
      { date: 'Mar 2026', amount: 4120, principal: 1462, interest: 2658, escrow: 0 },
    ],
    documents: [
      { name: 'Loan agreement', kind: 'Origination', status: 'held' },
      { name: 'Rate disclosure', kind: 'Disclosure', status: 'held' },
    ],
  },

  // ── HERO 2 — Early closure, prepared in the background ─────────────────────
  {
    id: 'c-1057',
    ref: 'MS-1057',
    type: 'early_closure',
    title: 'Early loan closure',
    customer: {
      name: 'Eleanor Whitmore',
      segment: 'Private Client',
      loanId: 'HL-3320815',
      product: '20-yr fixed home loan',
      balance: 284900,
      rate: 6.4,
      monthlyPayment: 2180,
      property: 'Austin, TX',
      tenureYears: 12,
      since: '2014',
    },
    stage: 'new',
    priority: 'normal',
    assignee: { kind: 'person', id: 'u-priya', label: 'Priya Nair' },
    openedDays: days(0),
    slaHours: 48,
    summary: 'Customer wants to pay off the loan in full and collect her property documents.',
    request:
      '“I’ve come into some money — I want to close the loan this month and get my property papers back.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [
      { id: 'a1', ts: 0, actor: 'system', text: 'Case created from secure message' },
    ],
    payments: [
      { date: 'May 2026', amount: 2180, principal: 660, interest: 1180, escrow: 340, note: 'Annual insurance renewal' },
      { date: 'Apr 2026', amount: 1840, principal: 672, interest: 1168, escrow: 0 },
      { date: 'Mar 2026', amount: 1840, principal: 668, interest: 1172, escrow: 0 },
    ],
    documents: [
      { name: 'Property title deed', kind: 'Custody', status: 'held' },
      { name: 'Original sale agreement', kind: 'Custody', status: 'held' },
      { name: 'Mortgage agreement', kind: 'Origination', status: 'held' },
      // Easy to miss in the list — the second charge the desk's workup catches.
      { name: 'Home-equity line — 2021', kind: 'Second charge', status: 'open' },
    ],
  },

  // ── Breadth — the rest of the worklist ────────────────────────────────────
  {
    id: 'c-1039',
    ref: 'MS-1039',
    type: 'document_request',
    title: 'Interest certificate request',
    customer: {
      name: 'Rosa Delgado',
      segment: 'Standard',
      loanId: 'HL-2210394',
      product: '15-yr fixed home loan',
      balance: 142300,
      rate: 5.9,
      monthlyPayment: 1190,
      property: 'Phoenix, AZ',
      tenureYears: 7,
      since: '2019',
    },
    stage: 'with_dept',
    priority: 'low',
    assignee: { kind: 'department', id: 'compliance', label: 'Compliance' },
    openedDays: days(2),
    slaHours: 72,
    summary: 'Year-end interest certificate for tax filing.',
    request: '“I need the interest statement for last year for my taxes.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'system', text: 'Routed to Compliance' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1044',
    ref: 'MS-1044',
    type: 'payment_dispute',
    title: 'Payment posted twice',
    customer: {
      name: 'Henry Okafor',
      segment: 'Premier',
      loanId: 'HL-5582013',
      product: '30-yr fixed home loan',
      balance: 488700,
      rate: 6.75,
      monthlyPayment: 3170,
      property: 'Atlanta, GA',
      tenureYears: 3,
      since: '2022',
    },
    stage: 'in_progress',
    priority: 'urgent',
    assignee: { kind: 'person', id: 'u-marcus', label: 'Marcus Bell' },
    openedDays: days(1),
    slaHours: 8,
    summary: 'Customer says May payment was debited twice; investigating with payments ops.',
    request: '“You took my payment twice this month. I need the second one back.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'advisor', text: 'Marcus Bell picked up the case' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1051',
    ref: 'MS-1051',
    type: 'hardship',
    title: 'Payment relief — job loss',
    customer: {
      name: 'Grace Lim',
      segment: 'Standard',
      loanId: 'HL-1190273',
      product: '30-yr fixed home loan',
      balance: 263100,
      rate: 6.2,
      monthlyPayment: 1610,
      property: 'Seattle, WA',
      tenureYears: 6,
      since: '2020',
    },
    stage: 'needs_approval',
    priority: 'high',
    assignee: { kind: 'person', id: 'u-dana', label: 'Dana Ortiz' },
    openedDays: days(3),
    slaHours: 48,
    summary: 'Customer requesting temporary payment relief after losing her job.',
    request: '“I lost my job last month. Can we pause or lower my payments for a while?”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'advisor', text: 'Dana Ortiz drafted a relief plan' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1036',
    ref: 'MS-1036',
    type: 'insurance_update',
    title: 'Home insurance update',
    customer: {
      name: 'Victor Reyes',
      segment: 'Standard',
      loanId: 'HL-7741200',
      product: '30-yr fixed home loan',
      balance: 351900,
      rate: 6.5,
      monthlyPayment: 2240,
      property: 'Denver, CO',
      tenureYears: 5,
      since: '2021',
    },
    stage: 'with_dept',
    priority: 'normal',
    assignee: { kind: 'department', id: 'insurance', label: 'Insurance & Escrow' },
    openedDays: days(4),
    slaHours: 72,
    summary: 'Customer switched home insurers; escrow needs updating.',
    request: '“I changed my home insurance — you need the new policy on file.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'system', text: 'Routed to Insurance & Escrow' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1029',
    ref: 'MS-1029',
    type: 'early_closure',
    title: 'Loan closure — property sold',
    customer: {
      name: 'Patel Family Trust',
      segment: 'Private Client',
      loanId: 'HL-9930012',
      product: '30-yr fixed home loan',
      balance: 712050,
      rate: 6.9,
      monthlyPayment: 4690,
      property: 'Fremont, CA',
      tenureYears: 8,
      since: '2018',
    },
    stage: 'done',
    priority: 'normal',
    assignee: { kind: 'person', id: 'u-sam', label: 'Sam Whitfield' },
    openedDays: days(9),
    slaHours: 48,
    summary: 'Loan closed on sale; documents released.',
    request: '“We sold the property — closing the loan at completion.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'system', text: 'Closed and documents released' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1063',
    ref: 'MS-1063',
    type: 'rate_change',
    title: 'Rate review after fixed term',
    customer: {
      name: 'Aaron Maldonado',
      segment: 'Premier',
      loanId: 'HL-6612740',
      product: '30-yr fixed home loan',
      balance: 524800,
      rate: 6.85,
      monthlyPayment: 3440,
      property: 'Portland, OR',
      tenureYears: 5,
      since: '2021',
    },
    stage: 'new',
    priority: 'normal',
    assignee: { kind: 'person', id: 'u-priya', label: 'Priya Nair' },
    openedDays: days(0),
    slaHours: 48,
    summary: 'Customer’s introductory fixed term is ending; wants to review options before reset.',
    request: '“My fixed term is almost up — what are my options before the rate resets?”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'system', text: 'Case created from secure message' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1055',
    ref: 'MS-1055',
    type: 'hardship',
    title: 'Payment relief — medical leave',
    customer: {
      name: 'Bianca Russo',
      segment: 'Standard',
      loanId: 'HL-3041188',
      product: '15-yr fixed home loan',
      balance: 198600,
      rate: 6.1,
      monthlyPayment: 1720,
      property: 'Columbus, OH',
      tenureYears: 4,
      since: '2022',
    },
    stage: 'in_progress',
    priority: 'high',
    assignee: { kind: 'person', id: 'u-priya', label: 'Priya Nair' },
    openedDays: days(1),
    slaHours: 48,
    summary: 'Customer on unpaid medical leave; asking for a short payment deferral.',
    request: '“I’m on medical leave for three months — can we defer payments until I’m back?”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'advisor', text: 'Priya Nair picked up the case' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1061',
    ref: 'MS-1061',
    type: 'rate_change',
    title: 'Retention rate match',
    customer: {
      name: 'Tomás Iglesias',
      segment: 'Premier',
      loanId: 'HL-7782034',
      product: '30-yr fixed home loan',
      balance: 605200,
      rate: 7.0,
      monthlyPayment: 4020,
      property: 'Miami, FL',
      tenureYears: 6,
      since: '2020',
    },
    stage: 'with_dept',
    priority: 'high',
    assignee: { kind: 'department', id: 'pricing', label: 'Pricing' },
    openedDays: days(2),
    slaHours: 24,
    summary: 'Customer brought a competitor offer; Pricing reviewing a retention match.',
    request: '“Another lender quoted me lower — can you match it or I’ll refinance away.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'agent', text: 'Routed to Pricing for a retention quote' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1048',
    ref: 'MS-1048',
    type: 'early_closure',
    title: 'Payoff quote — refinancing away',
    customer: {
      name: 'Nadia Haddad',
      segment: 'Private Client',
      loanId: 'HL-5510267',
      product: '20-yr fixed home loan',
      balance: 333400,
      rate: 6.6,
      monthlyPayment: 2510,
      property: 'Boston, MA',
      tenureYears: 9,
      since: '2017',
    },
    stage: 'with_dept',
    priority: 'normal',
    assignee: { kind: 'department', id: 'closures', label: 'Closures & Payoffs' },
    openedDays: days(3),
    slaHours: 48,
    summary: 'Customer refinancing with another lender; needs a 10-day payoff figure.',
    request: '“I’m refinancing elsewhere — I need an official payoff figure good for ten days.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'agent', text: 'Routed to Closures & Payoffs' }],
    payments: [],
    documents: [
      { name: 'Property title deed', kind: 'Custody', status: 'held' },
      { name: 'Mortgage agreement', kind: 'Origination', status: 'held' },
    ],
  },
  {
    id: 'c-1033',
    ref: 'MS-1033',
    type: 'document_request',
    title: 'Title deed release on completion',
    customer: {
      name: 'Walter Ndiaye',
      segment: 'Premier',
      loanId: 'HL-2294510',
      product: '30-yr fixed home loan',
      balance: 0,
      rate: 6.3,
      monthlyPayment: 0,
      property: 'Sacramento, CA',
      tenureYears: 11,
      since: '2015',
    },
    stage: 'with_dept',
    priority: 'normal',
    assignee: { kind: 'department', id: 'legal', label: 'Legal & Custody' },
    openedDays: days(5),
    slaHours: 72,
    summary: 'Loan fully repaid; customer requesting release of the original title deed.',
    request: '“My loan’s paid off — I’d like my original title deed back, please.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'agent', text: 'Routed to Legal & Custody for deed release' }],
    payments: [],
    documents: [
      { name: 'Property title deed', kind: 'Custody', status: 'held' },
      { name: 'Discharge of mortgage', kind: 'Custody', status: 'pending' },
    ],
  },
  {
    id: 'c-1031',
    ref: 'MS-1031',
    type: 'payment_dispute',
    title: 'Escrow shortfall dispute',
    customer: {
      name: 'Priscilla Vance',
      segment: 'Standard',
      loanId: 'HL-8830451',
      product: '30-yr fixed home loan',
      balance: 274500,
      rate: 6.45,
      monthlyPayment: 1980,
      property: 'Nashville, TN',
      tenureYears: 7,
      since: '2019',
    },
    stage: 'new',
    priority: 'normal',
    assignee: { kind: 'person', id: 'u-marcus', label: 'Marcus Bell' },
    openedDays: days(0),
    slaHours: 48,
    summary: 'Customer disputes an escrow shortfall after a property-tax reassessment.',
    request: '“My payment jumped and I don’t agree with the escrow shortfall you’re charging.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'system', text: 'Case created from inbound call' }],
    payments: [],
    documents: [],
  },
  {
    id: 'c-1018',
    ref: 'MS-1018',
    type: 'insurance_update',
    title: 'Flood policy lapse',
    customer: {
      name: 'Desmond Carter',
      segment: 'Standard',
      loanId: 'HL-4417823',
      product: '30-yr fixed home loan',
      balance: 389200,
      rate: 6.55,
      monthlyPayment: 2470,
      property: 'New Orleans, LA',
      tenureYears: 6,
      since: '2020',
    },
    stage: 'done',
    priority: 'low',
    assignee: { kind: 'person', id: 'u-dana', label: 'Dana Ortiz' },
    openedDays: days(7),
    slaHours: 72,
    summary: 'Flood policy had lapsed; replacement policy received and escrow updated.',
    request: '“I renewed my flood cover with a new insurer — here’s the policy.”',
    preparing: false,
    jobs: [],
    approvals: [],
    activity: [{ id: 'a1', ts: 0, actor: 'system', text: 'New policy on file; escrow updated' }],
    payments: [],
    documents: [],
  },
];

// Authored notes seeded on a few cases, so the comments thread reads as a live
// workspace rather than starting empty. Keyed by case ref.
const SEED_COMMENTS: Record<string, Comment[]> = {
  'MS-1039': [
    {
      id: 'cm-1039-1',
      ts: 0,
      author: 'Priya Nair',
      authorKind: 'advisor',
      text: 'Routing to Compliance — certificate needs the prior tax-year figures, not the current one. Flagging so they pull the right period.',
      dept: 'compliance',
      deptLabel: 'Compliance',
    },
  ],
  'MS-1061': [
    {
      id: 'cm-1061-1',
      ts: 0,
      author: 'Priya Nair',
      authorKind: 'advisor',
      text: 'Competitor quote attached to the call notes. Customer is a 6-year Premier — worth a genuine retention match, not just the floor.',
      dept: 'pricing',
      deptLabel: 'Pricing',
    },
  ],
  'MS-1048': [
    {
      id: 'cm-1048-1',
      ts: 0,
      author: 'Marcus Bell',
      authorKind: 'advisor',
      text: 'Payoff must be valid for 10 days for their new lender. Closures to date the quote accordingly.',
      dept: 'closures',
      deptLabel: 'Closures & Payoffs',
    },
  ],
};

const CASES: Case[] = RAW_CASES.map((c) => ({
  ...c,
  findings: [],
  blocker: null,
  packet: null,
  comments: SEED_COMMENTS[c.ref] ?? [],
}));

export const WORKSPACE: Workspace = {
  advisor: ADVISOR,
  team: TEAM,
  departments: DEPARTMENTS,
  cases: CASES,
};
