/**
 * The dock — Aria in the corner of the bank site: a launcher before the call, and
 * during it a **picture-in-picture meeting tile**.
 *
 * One component for both, and deliberately so. The thing the customer clicks and
 * the thing that answers them are the same object in the same corner, so the
 * call *opens* rather than appearing somewhere else; a launcher that vanishes
 * and a panel that materialises across the page reads as two products.
 *
 * Bottom-right, because that is where a bank site's assistant lives and where
 * this bank's current one already is. The two transient cards the demo puts on
 * screen — the ticket reference and the contact panel — moved to the left to
 * make room (`pages.tsx`, `tools.tsx`); they are the only other floating things
 * here, and having them share a corner with Aria meant covering her at the exact
 * moment she raised a request.
 *
 * Everything it carries is *additive*: the ambient edge glow still says what the
 * call is doing peripherally. Nothing here replaces it; it is the demo's
 * argument, and this is what sits on top of it.
 *
 * ## Why a meeting tile
 *
 * The live tile is shaped like the picture-in-picture window of a video call —
 * a state chip and a running timer over the face, a name plate in the corner,
 * captions across the bottom, and **the controls directly under the picture**.
 * That shape is doing work: a customer who has ever been in a video call knows
 * without being told that this is a conversation with someone, that the thing
 * under the picture mutes them, and that the red one hangs up. Controls in the
 * bank's own navigation row and a transcript floating somewhere else were two
 * halves of one call in two places, which is the arrangement this replaces.
 *
 * Two axes, both switchable mid-call, because a demo is watched by people with
 * different questions: `size` (`compact` shrinks the face when the page matters
 * more than the presenter) and `chat` (the transcript column, off by default).
 *
 * **The face.** `@voqalize/avatar` (MIT, npm) with the `myna` rig. It takes one
 * prop that matters — the live `PipecatClient` — and drives itself off the
 * `avatar` server messages Voqalize's runtime already sends over the same data
 * channel the transcript rides. There is nothing to configure and no second
 * stream: no video track, no talking-head vendor, no per-minute cost. The rig
 * only renders; the server owns the intent.
 *
 * Before the call there is no client to embody, so the launcher wears a **still**
 * of the same face — `aria-portrait.svg`, one frame of the same rig, generated by
 * `tools/render-portrait.mjs`.
 *
 * **The transcript and the composer are voice-ui-kit's**, not ours. `Conversation`
 * renders Aria's half in *karaoke*: the words TTS has already spoken in full ink,
 * the words it has not yet reached dimmed, filling in as she says them —
 * `BotOutputText {spoken, unspoken}` off the same stream, which our own list used
 * to concatenate and discard. `noFunctionCalls` keeps the tool traffic out of it
 * by construction rather than by a filter we maintain: Aria's tools drive the
 * screen, and the screen is where a customer reads them.
 *
 * `TextInput` is the kit's too, and it does exactly what our hand-rolled composer
 * did, for the same reason: a typed sentence never passes a recognizer, so no
 * `user-transcription` ever comes back for it and the message has to be injected
 * locally before `sendText`. Typing reaches the brain as an ordinary user turn
 * and is answered aloud — `on_user_message` cannot tell it was typed.
 *
 * The kit's stylesheet is Tailwind and 132 KB, which is not something to unleash
 * on a bank-branded page — so this imports `styles.scoped`, which scopes every
 * rule under `.vkui-root`, and only the tile wears that class. `pages.tsx` is
 * untouched. Our own rules below are unlayered and therefore win over the kit's
 * `@layer base` reset inside the tile.
 */

import { useEffect, useRef, useState } from 'react';
import type { PipecatClient } from '@pipecat-ai/client-js';
import {
  BotAudioControl,
  Conversation,
  ControlBar,
  ControlBarDivider,
  TextInput,
  TranscriptOverlay,
  UserAudioControl,
} from '@pipecat-ai/voice-ui-kit';
import '@pipecat-ai/voice-ui-kit/styles.scoped';
import { Avatar } from '@voqalize/avatar/react';
import { myna } from '@voqalize/avatar/faces/myna';
import { Maximize2, MessageSquare, Minimize2, PhoneOff } from 'lucide-react';
import type { AmbientPresenceActivity } from '@voqalize/demo-kit';
import portrait from './aria-portrait.svg';

const PRIMARY = '#4F46E5';
const ACCENT = '#8B5CF6';

const ACTIVITY_LABEL: Record<AmbientPresenceActivity, string> = {
  idle: 'Listening',
  listening: 'Listening',
  thinking: 'Working on it',
  speaking: 'Speaking',
};

// ── The dock ──────────────────────────────────────────────────────────────────

export interface AuraDockProps {
  /**
   * The client. `null` only in the moment before the host has built one. The
   * launcher no longer needs it — it wears a still — so this matters only once
   * the call is live.
   */
  client: PipecatClient | null;
  /** What the call is doing, from the same turn-taking events the ring reads. */
  activity: AmbientPresenceActivity;
  /** Whether to mount the avatar rig. `?avatar=0` turns it off. */
  avatar: boolean;
  /** Whether the chat column starts open. `?chat=1` opens it. */
  chat: boolean;
  /**
   * Where the call is. `idle` and `connecting` show the launcher; `live` shows
   * the tile. The host decides this — the dock deliberately reads no transport
   * state of its own, so there is one place that knows what phase we are in.
   */
  phase: 'idle' | 'connecting' | 'live';
  /** Open the pre-call sheet. The dock never connects; it asks. */
  onStart: () => void;
  /** Hang up. The red button in the control bar is the only way out of a call. */
  onEnd: () => void;
}

export function AuraDock({ client, activity, avatar, chat, phase, onStart, onEnd }: AuraDockProps) {
  const [chatOpen, setChatOpen] = useState(chat);
  const [size, setSize] = useState<'compact' | 'full'>('full');

  // Before the call: one launcher, and nothing else of ours on the page. A bank
  // site should look like a bank site until the customer asks for help.
  if (phase !== 'live') {
    return (
      <>
        <Launcher connecting={phase === 'connecting'} onStart={onStart} />
        <DockStyles />
      </>
    );
  }

  return (
    <>
      {/* `vkui-root` is the whole contract with voice-ui-kit's stylesheet: its
          variables and utilities apply inside this element and nowhere else. */}
      <aside
        className={`vkui-root aura-tile is-${size} is-${activity}${chatOpen ? ' has-chat' : ''}`}
        aria-label="Call with Aria"
      >
        {avatar ? (
          <div className="aura-tile-stage">
            {/* Driven entirely by the runtime's own `avatar` messages on the
                data channel — the client is the only prop it needs. */}
            <Avatar options={{ face: myna }} client={client} aria-label="Aria" />
            <div className="aura-tile-chip">
              <span className={`aura-tile-dot is-${activity}`} aria-hidden />
              <span>{ACTIVITY_LABEL[activity]}</span>
              <CallTimer />
            </div>
            <span className="aura-tile-plate">Aria · Aura Support</span>
            {/* The caption band: Aria's current sentence, word by word, over the
                picture. The chat column below is the history; this is the
                sentence in flight, and it is the half a customer glances at. */}
            <div className="aura-tile-captions">
              <TranscriptOverlay participant="remote" size="sm" />
            </div>
          </div>
        ) : (
          <header className="aura-tile-head">
            <span className={`aura-tile-dot is-${activity}`} aria-hidden />
            <span className="aura-tile-name">Aria</span>
            <span className="aura-tile-state">{ACTIVITY_LABEL[activity]}</span>
            <CallTimer />
          </header>
        )}

        {/* Directly under the picture, where a decade of video calls has taught
            everyone to look for them. */}
        <div className="aura-tile-bar">
          <ControlBar noAnimateIn className="aura-tile-controls">
            <UserAudioControl
              size="sm"
              variant="outline"
              noSpeakers
              visualizerProps={{ barCount: 5 }}
            />
            <BotAudioControl size="sm" variant="outline" />
            <ControlBarDivider />
            {avatar ? (
              <button
                type="button"
                className={`aura-tile-btn${size === 'compact' ? ' is-on' : ''}`}
                onClick={() => setSize(size === 'full' ? 'compact' : 'full')}
                aria-pressed={size === 'compact'}
                title={size === 'full' ? 'Shrink Aria' : 'Enlarge Aria'}
              >
                {size === 'full' ? <Minimize2 size={15} /> : <Maximize2 size={15} />}
              </button>
            ) : null}
            <button
              type="button"
              className={`aura-tile-btn${chatOpen ? ' is-on' : ''}`}
              onClick={() => setChatOpen(!chatOpen)}
              aria-pressed={chatOpen}
              title={chatOpen ? 'Hide chat' : 'Show chat'}
            >
              <MessageSquare size={15} />
            </button>
            <button type="button" className="aura-tile-end" onClick={onEnd} title="End call">
              <PhoneOff size={15} />
            </button>
          </ControlBar>
        </div>

        {chatOpen ? (
          <div className="aura-tile-chat">
            <div className="aura-tile-log">
              <Conversation
                assistantLabel="Aria"
                clientLabel="You"
                textRenderMode="karaoke"
                noFunctionCalls
                noTextInput
              />
            </div>
            <div className="aura-tile-composer">
              <TextInput size="sm" placeholder="Type a question…" />
            </div>
          </div>
        ) : null}
      </aside>
      <DockStyles />
    </>
  );
}

/**
 * How long the call has been up.
 *
 * Nothing says "you are in a call" faster, and it is the one piece of meeting
 * furniture we had none of. It counts from mount, which is when the tile first
 * renders — i.e. when the transport reported connected.
 */
function CallTimer() {
  const started = useRef(Date.now());
  const [now, setNow] = useState(Date.now());
  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);
  const s = Math.max(0, Math.floor((now - started.current) / 1000));
  const mm = String(Math.floor(s / 60)).padStart(2, '0');
  const ss = String(s % 60).padStart(2, '0');
  return (
    <time className="aura-tile-clock" dateTime={`PT${s}S`}>
      {mm}:{ss}
    </time>
  );
}

/**
 * The launcher — the only thing this demo puts on a bank page nobody has asked
 * for help on yet.
 *
 * It wears a **still** of the face that will answer. That is a change of mind:
 * it used to mount the live rig, on the argument that a customer decides whether
 * to talk to an assistant by looking at it. The argument was right and the
 * execution was not — a bust drawn for a 4:3 call tile, scaled 1.9× and clipped
 * to a 52 px circle, is a floating head, and one that blinks at you while you
 * are reading about interest certificates. A still portrait, cropped square at
 * the source (`tools/render-portrait.mjs`), is the same promise made quietly.
 *
 * It says "Talk to Aria" rather than "Chat with us" because it is a *voice*
 * assistant and a customer who expects a text box and is asked for a microphone
 * has been misled by us, not by the browser. Clicking opens the pre-call sheet
 * — this button never connects on its own; the microphone opens one deliberate
 * step later, behind the notice.
 */
function Launcher({ connecting, onStart }: { connecting: boolean; onStart: () => void }) {
  return (
    <button
      type="button"
      className={`aura-aria-launch${connecting ? ' is-busy' : ''}`}
      onClick={onStart}
      disabled={connecting}
      aria-label={connecting ? 'Connecting to Aria' : 'Talk to Aria, the voice assistant'}
    >
      <span className="aura-aria-launch-face">
        <img src={portrait} alt="" width={52} height={52} />
      </span>
      <span className="aura-aria-launch-copy">
        <span className="aura-aria-launch-title">{connecting ? 'Connecting…' : 'Talk to Aria'}</span>
        <span className="aura-aria-launch-sub">
          {connecting ? 'One moment' : 'Aura’s voice assistant'}
        </span>
      </span>
    </button>
  );
}

function DockStyles() {
  return (
    <style>{`
      /* Bottom-right — the corner a customer already reaches for, and the corner
         the bank's current assistant occupies. The demo's own transient cards
         (the ticket reference, the contact panel) were here first and moved to
         the left to make room; see pages.tsx and tools.tsx. */
      .aura-tile {
        position: fixed;
        right: 20px;
        bottom: 20px;
        z-index: 200;
        width: 332px;
        display: flex;
        flex-direction: column;
        background: #FFFFFF;
        border: 1px solid #E6E2F2;
        border-radius: 16px;
        box-shadow: 0 18px 48px rgba(26,22,32,.20);
        overflow: hidden;
        font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
        animation: aura-aria-rise .22s cubic-bezier(.2,.7,.3,1);
        transition: box-shadow .25s ease;
      }
      /* She is speaking: the tile is lit from its own edge, the way a meeting
         tile rings the active speaker. Same source as the ambient glow. */
      .aura-tile.is-speaking { box-shadow: 0 18px 48px rgba(26,22,32,.20), 0 0 0 3px rgba(139,92,246,.34); }
      .aura-tile.is-listening { box-shadow: 0 18px 48px rgba(26,22,32,.20), 0 0 0 3px rgba(79,70,229,.22); }
      @keyframes aura-aria-rise {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: none; }
      }

      /* The picture. A neutral ground rather than a lavender wash is what makes
         it read as a video feed instead of an illustration panel. */
      .aura-tile-stage {
        position: relative;
        flex: none;
        height: 214px;
        background: linear-gradient(168deg, #EEF0FE 0%, #E4E2F6 100%);
        transition: height .22s cubic-bezier(.2,.7,.3,1);
      }
      .aura-tile.is-compact .aura-tile-stage { height: 116px; }
      .aura-tile-stage > [role="img"] { width: 100%; height: 100%; }
      .aura-tile-chip {
        position: absolute;
        top: 9px;
        left: 9px;
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 4px 9px;
        border-radius: 999px;
        background: rgba(26,22,32,.62);
        backdrop-filter: blur(6px);
        color: #fff;
        font-size: 11px;
        font-weight: 650;
        letter-spacing: .01em;
      }
      .aura-tile-clock { font-variant-numeric: tabular-nums; opacity: .82; }
      .aura-tile-dot {
        width: 7px;
        height: 7px;
        border-radius: 50%;
        background: #34D399;
        flex: none;
        transition: background .2s ease;
      }
      .aura-tile-dot.is-thinking { background: #F0A020; }
      .aura-tile-dot.is-speaking { background: ${ACCENT}; }
      .aura-tile-plate {
        position: absolute;
        left: 9px;
        bottom: 9px;
        padding: 3px 9px;
        border-radius: 8px;
        background: rgba(26,22,32,.55);
        backdrop-filter: blur(6px);
        color: #fff;
        font-size: 11px;
        font-weight: 600;
      }
      /* Captions sit above the name plate and clear of the mouth. */
      .aura-tile-captions {
        position: absolute;
        left: 10px;
        right: 10px;
        bottom: 34px;
        display: flex;
        justify-content: center;
        pointer-events: none;
        text-align: center;
      }
      .aura-tile-captions > * {
        max-width: 100%;
        padding: 5px 9px;
        border-radius: 9px;
        background: rgba(26,22,32,.72);
        color: #fff;
        font-size: 12px;
        line-height: 1.4;
      }
      /* With the chat column open the caption band is the same sentence twice,
         a few pixels apart. The captions are what a *closed* chat leaves behind. */
      .aura-tile.has-chat .aura-tile-captions { display: none; }

      /* No face (?avatar=0): a plain header carries the same three facts. */
      .aura-tile-head {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 11px 13px;
        flex: none;
      }
      .aura-tile-name { font-size: 13.5px; font-weight: 750; color: #1A1620; }
      .aura-tile-state { font-size: 12px; color: #A79FB2; }
      .aura-tile-head .aura-tile-clock { margin-left: auto; font-size: 12px; color: #A79FB2; }

      .aura-tile-bar {
        flex: none;
        border-top: 1px solid #EFEDF7;
        padding: 8px 9px;
        background: #FCFBFF;
      }
      .aura-tile-controls {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 6px;
        border: none;
        background: none;
        box-shadow: none;
        padding: 0;
      }
      .aura-tile-btn, .aura-tile-end {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 32px;
        height: 32px;
        border-radius: 9px;
        border: 1px solid #E6E2F2;
        background: #fff;
        color: #6E6470;
        cursor: pointer;
        flex: none;
        transition: color .15s ease, border-color .15s ease, background .15s ease;
      }
      .aura-tile-btn:hover { color: ${PRIMARY}; border-color: #C7C2E8; }
      .aura-tile-btn.is-on { background: #EEF0FE; color: ${PRIMARY}; border-color: #C7C2E8; }
      .aura-tile-end {
        margin-left: 2px;
        border-color: transparent;
        background: #E23B3B;
        color: #fff;
      }
      .aura-tile-end:hover { background: #C92F2F; }

      .aura-tile-chat {
        display: flex;
        flex-direction: column;
        min-height: 0;
        border-top: 1px solid #EFEDF7;
      }
      /* The kit's Conversation fills its container, so the container is what
         decides how much history is on screen. */
      .aura-tile-log {
        height: 224px;
        font-size: 13px;
      }
      /* A short history sits on the floor of the log, the way a chat does,
         instead of hanging from the ceiling above a field of white. The kit's
         scroller holds the whole list in one unclassed div, so an auto top
         margin on that div does it — and unlike justify-content: flex-end on
         the scroller, an auto margin collapses once the list is taller than the
         box, which leaves the overflowing top reachable. */
      .aura-tile-log [class*="overflow-y-auto"] {
        display: flex;
        flex-direction: column;
      }
      .aura-tile-log [class*="overflow-y-auto"] > * { margin-top: auto; }
      .aura-tile.is-compact .aura-tile-log { height: 272px; }
      .aura-tile-composer {
        flex: none;
        padding: 9px 10px;
        border-top: 1px solid #EFEDF7;
      }

      /* The launcher. */
      .aura-aria-launch {
        position: fixed;
        right: 20px;
        bottom: 20px;
        z-index: 200;
        display: flex;
        align-items: center;
        gap: 11px;
        padding: 8px 18px 8px 8px;
        border-radius: 999px;
        border: 1px solid #E6E2F2;
        background: #fff;
        box-shadow: 0 14px 34px rgba(26,22,32,.17);
        cursor: pointer;
        font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
        text-align: left;
        transition: transform .16s ease, box-shadow .16s ease, border-color .16s ease;
        animation: aura-aria-rise .3s cubic-bezier(.2,.7,.3,1);
      }
      .aura-aria-launch:hover:not(:disabled) {
        transform: translateY(-2px);
        border-color: #C7C2E8;
        box-shadow: 0 20px 44px rgba(26,22,32,.22);
      }
      .aura-aria-launch:disabled { cursor: default; }
      .aura-aria-launch-face {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 52px;
        height: 52px;
        flex: none;
        border-radius: 50%;
        overflow: hidden;
        background: linear-gradient(160deg, #F5F3FF 0%, #EEF0FE 100%);
      }
      /* The still is cropped square at the source, so it needs no transform. */
      .aura-aria-launch-face img { width: 100%; height: 100%; display: block; }
      .aura-aria-launch-copy {
        display: flex;
        flex-direction: column;
        gap: 2px;
      }
      .aura-aria-launch-title { font-size: 14px; font-weight: 750; color: #1A1620; }
      .aura-aria-launch-sub { font-size: 11.5px; color: #7C7488; }
      .aura-aria-launch.is-busy .aura-aria-launch-sub { color: ${PRIMARY}; }

      @media (max-width: 720px) {
        .aura-tile {
          left: 12px;
          right: 12px;
          bottom: 12px;
          width: auto;
        }
        .aura-tile-stage { height: 168px; }
        .aura-tile.is-compact .aura-tile-stage { height: 96px; }
        .aura-tile-log { height: 176px; }
        .aura-aria-launch { right: 12px; bottom: 12px; }
      }
    `}</style>
  );
}
