// Voqalize cortex wire frames.
//
// This schema is the canonical wire vocabulary between:
//   - the voice runtime (pygato / gato) and cortex
//   - the agent SDK (CortexAgent)       and cortex
//
// Cortex itself is byte-opaque; this schema is consumed only by the two
// endpoints. Generated stubs are committed alongside each SDK:
//   - sdk/python/src/voqalize/sdk/wire/_frames_pb2.py
//   - sdk/go/wire/framespb/frames.pb.go
//
// Regenerate with `make proto` (root Makefile, driven by `buf generate`).
//
// Field-number policy in `Envelope.body`:
//   1 – 30   reserved for Vql application frames
//   31 +     reserved for pipeline lifecycle / transport frames
//
// Opaque dict fields (`payload`, function call `arguments` / `result`) are
// JSON-encoded `string`, matching pipecat's `MessageFrame.data` pattern.
// No `google.protobuf.Struct` dependency.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: voqalize/frames/frames.proto

package framespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Why a finalize was emitted. interrupted == true iff reason == USER_BARGE_IN;
// both are kept because consumers key off either the bool (cheap) or the reason
// (extensible). UNSPECIFIED never appears on the wire — the sender always sets it.
type FinalizeReason int32

const (
	FinalizeReason_FINALIZE_REASON_UNSPECIFIED   FinalizeReason = 0
	FinalizeReason_FINALIZE_REASON_COMPLETED     FinalizeReason = 1
	FinalizeReason_FINALIZE_REASON_USER_BARGE_IN FinalizeReason = 2
)

// Enum value maps for FinalizeReason.
var (
	FinalizeReason_name = map[int32]string{
		0: "FINALIZE_REASON_UNSPECIFIED",
		1: "FINALIZE_REASON_COMPLETED",
		2: "FINALIZE_REASON_USER_BARGE_IN",
	}
	FinalizeReason_value = map[string]int32{
		"FINALIZE_REASON_UNSPECIFIED":   0,
		"FINALIZE_REASON_COMPLETED":     1,
		"FINALIZE_REASON_USER_BARGE_IN": 2,
	}
)

func (x FinalizeReason) Enum() *FinalizeReason {
	p := new(FinalizeReason)
	*p = x
	return p
}

func (x FinalizeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalizeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_voqalize_frames_frames_proto_enumTypes[0].Descriptor()
}

func (FinalizeReason) Type() protoreflect.EnumType {
	return &file_voqalize_frames_frames_proto_enumTypes[0]
}

func (x FinalizeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalizeReason.Descriptor instead.
func (FinalizeReason) EnumDescriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{0}
}

// Top-level message carried in each websocket binary payload.
// Wire layout: [1 byte direction] [Envelope serialized bytes].
//
// Ordering ack protocol (CortexLLMService ↔ CortexAgent):
//   - The pygato bridge tags outbound data frames with `request_id` (a
//     monotonically increasing uint64).
//   - The agent SDK, after the customer's `process_frame` returns for that
//     frame, sends an `Ack { ack_id = request_id }` envelope back over the
//     wire. The bridge resolves the pending future to unblock its own
//     `process_frame`, which releases pipecat's next queued frame.
//   - Lifecycle frames (Vql*Start/Interruption/End/Cancel) and SystemFrames
//     are not ack-gated — they have no `request_id`.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// COMPATIBILITY RULE — this oneof is ADD-ONLY.
	//
	// PyGato and the Brains that talk to it deploy independently and promote at
	// different times (dev-first for pygato, both-envs-at-once for the demo
	// brains), so at any moment an old sender can be talking to a new receiver or
	// vice versa. Protobuf drops an unknown oneof field silently, which turns a
	// renumbering into a frame that vanishes with no error.
	//
	// Therefore: NEVER remove a field, NEVER renumber one, and never repurpose a
	// retired number. A new capability is either a new OPTIONAL field appended to
	// an existing message (absent == the old behaviour) or an entirely new frame
	// number — and it must be DEFAULT-OFF, so a peer that has never heard of it
	// behaves exactly as before.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_VqlStart
	//	*Envelope_VqlUserText
	//	*Envelope_VqlInterruption
	//	*Envelope_VqlInferenceFinalized
	//	*Envelope_VqlLlmStart
	//	*Envelope_VqlLlmText
	//	*Envelope_VqlLlmEnd
	//	*Envelope_VqlFcStarted
	//	*Envelope_VqlFcInProgress
	//	*Envelope_VqlFcResult
	//	*Envelope_VqlInteractionCompleted
	//	*Envelope_VqlUserIdle
	//	*Envelope_End
	//	*Envelope_Cancel
	//	*Envelope_Error
	//	*Envelope_RtviServerMessage
	//	*Envelope_SttUpdateSettings
	//	*Envelope_TtsUpdateSettings
	//	*Envelope_RtviClientMessage
	//	*Envelope_IdleUpdateSettings
	//	*Envelope_Ack
	Body isEnvelope_Body `protobuf_oneof:"body"`
	// Set by the sender on data frames that require an ack back. Zero / absent
	// means "no ack expected." Bridge-scoped counter starting at 1; receiver
	// does not need to interpret the value, only echo it.
	RequestId     uint64 `protobuf:"varint,50,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetVqlStart() *VqlStart {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlStart); ok {
			return x.VqlStart
		}
	}
	return nil
}

func (x *Envelope) GetVqlUserText() *VqlUserText {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlUserText); ok {
			return x.VqlUserText
		}
	}
	return nil
}

func (x *Envelope) GetVqlInterruption() *VqlInterruption {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlInterruption); ok {
			return x.VqlInterruption
		}
	}
	return nil
}

func (x *Envelope) GetVqlInferenceFinalized() *VqlInferenceFinalized {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlInferenceFinalized); ok {
			return x.VqlInferenceFinalized
		}
	}
	return nil
}

func (x *Envelope) GetVqlLlmStart() *VqlLLMFullResponseStart {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlLlmStart); ok {
			return x.VqlLlmStart
		}
	}
	return nil
}

func (x *Envelope) GetVqlLlmText() *VqlLLMText {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlLlmText); ok {
			return x.VqlLlmText
		}
	}
	return nil
}

func (x *Envelope) GetVqlLlmEnd() *VqlLLMFullResponseEnd {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlLlmEnd); ok {
			return x.VqlLlmEnd
		}
	}
	return nil
}

func (x *Envelope) GetVqlFcStarted() *VqlFunctionCallsStarted {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlFcStarted); ok {
			return x.VqlFcStarted
		}
	}
	return nil
}

func (x *Envelope) GetVqlFcInProgress() *VqlFunctionCallInProgress {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlFcInProgress); ok {
			return x.VqlFcInProgress
		}
	}
	return nil
}

func (x *Envelope) GetVqlFcResult() *VqlFunctionCallResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlFcResult); ok {
			return x.VqlFcResult
		}
	}
	return nil
}

func (x *Envelope) GetVqlInteractionCompleted() *VqlInteractionCompleted {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlInteractionCompleted); ok {
			return x.VqlInteractionCompleted
		}
	}
	return nil
}

func (x *Envelope) GetVqlUserIdle() *VqlUserIdle {
	if x != nil {
		if x, ok := x.Body.(*Envelope_VqlUserIdle); ok {
			return x.VqlUserIdle
		}
	}
	return nil
}

func (x *Envelope) GetEnd() *End {
	if x != nil {
		if x, ok := x.Body.(*Envelope_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *Envelope) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetRtviServerMessage() *RTVIServerMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RtviServerMessage); ok {
			return x.RtviServerMessage
		}
	}
	return nil
}

func (x *Envelope) GetSttUpdateSettings() *STTUpdateSettings {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SttUpdateSettings); ok {
			return x.SttUpdateSettings
		}
	}
	return nil
}

func (x *Envelope) GetTtsUpdateSettings() *TTSUpdateSettings {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TtsUpdateSettings); ok {
			return x.TtsUpdateSettings
		}
	}
	return nil
}

func (x *Envelope) GetRtviClientMessage() *RTVIClientMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RtviClientMessage); ok {
			return x.RtviClientMessage
		}
	}
	return nil
}

func (x *Envelope) GetIdleUpdateSettings() *IdleUpdateSettings {
	if x != nil {
		if x, ok := x.Body.(*Envelope_IdleUpdateSettings); ok {
			return x.IdleUpdateSettings
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_VqlStart struct {
	// Vql application frames (1 – 30)
	VqlStart *VqlStart `protobuf:"bytes,1,opt,name=vql_start,json=vqlStart,proto3,oneof"`
}

type Envelope_VqlUserText struct {
	VqlUserText *VqlUserText `protobuf:"bytes,2,opt,name=vql_user_text,json=vqlUserText,proto3,oneof"`
}

type Envelope_VqlInterruption struct {
	VqlInterruption *VqlInterruption `protobuf:"bytes,3,opt,name=vql_interruption,json=vqlInterruption,proto3,oneof"`
}

type Envelope_VqlInferenceFinalized struct {
	VqlInferenceFinalized *VqlInferenceFinalized `protobuf:"bytes,4,opt,name=vql_inference_finalized,json=vqlInferenceFinalized,proto3,oneof"`
}

type Envelope_VqlLlmStart struct {
	VqlLlmStart *VqlLLMFullResponseStart `protobuf:"bytes,5,opt,name=vql_llm_start,json=vqlLlmStart,proto3,oneof"`
}

type Envelope_VqlLlmText struct {
	VqlLlmText *VqlLLMText `protobuf:"bytes,6,opt,name=vql_llm_text,json=vqlLlmText,proto3,oneof"`
}

type Envelope_VqlLlmEnd struct {
	VqlLlmEnd *VqlLLMFullResponseEnd `protobuf:"bytes,7,opt,name=vql_llm_end,json=vqlLlmEnd,proto3,oneof"`
}

type Envelope_VqlFcStarted struct {
	VqlFcStarted *VqlFunctionCallsStarted `protobuf:"bytes,8,opt,name=vql_fc_started,json=vqlFcStarted,proto3,oneof"`
}

type Envelope_VqlFcInProgress struct {
	VqlFcInProgress *VqlFunctionCallInProgress `protobuf:"bytes,9,opt,name=vql_fc_in_progress,json=vqlFcInProgress,proto3,oneof"`
}

type Envelope_VqlFcResult struct {
	VqlFcResult *VqlFunctionCallResult `protobuf:"bytes,10,opt,name=vql_fc_result,json=vqlFcResult,proto3,oneof"`
}

type Envelope_VqlInteractionCompleted struct {
	VqlInteractionCompleted *VqlInteractionCompleted `protobuf:"bytes,11,opt,name=vql_interaction_completed,json=vqlInteractionCompleted,proto3,oneof"`
}

type Envelope_VqlUserIdle struct {
	VqlUserIdle *VqlUserIdle `protobuf:"bytes,12,opt,name=vql_user_idle,json=vqlUserIdle,proto3,oneof"`
}

type Envelope_End struct {
	// Pipeline lifecycle / transport frames (31+)
	End *End `protobuf:"bytes,31,opt,name=end,proto3,oneof"`
}

type Envelope_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,32,opt,name=cancel,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,33,opt,name=error,proto3,oneof"`
}

type Envelope_RtviServerMessage struct {
	// Pipecat-native frames that ride the cortex wire.
	// These are NOT Vql vocabulary — they wrap pipecat's own frame types so
	// a customer agent can drive pygato's STT/TTS/RTVI processors over the
	// wire. JSON-encoded dicts; the deserialized frame reconstructs the
	// pipecat-native type.
	RtviServerMessage *RTVIServerMessage `protobuf:"bytes,34,opt,name=rtvi_server_message,json=rtviServerMessage,proto3,oneof"`
}

type Envelope_SttUpdateSettings struct {
	SttUpdateSettings *STTUpdateSettings `protobuf:"bytes,35,opt,name=stt_update_settings,json=sttUpdateSettings,proto3,oneof"`
}

type Envelope_TtsUpdateSettings struct {
	TtsUpdateSettings *TTSUpdateSettings `protobuf:"bytes,36,opt,name=tts_update_settings,json=ttsUpdateSettings,proto3,oneof"`
}

type Envelope_RtviClientMessage struct {
	RtviClientMessage *RTVIClientMessage `protobuf:"bytes,37,opt,name=rtvi_client_message,json=rtviClientMessage,proto3,oneof"`
}

type Envelope_IdleUpdateSettings struct {
	IdleUpdateSettings *IdleUpdateSettings `protobuf:"bytes,38,opt,name=idle_update_settings,json=idleUpdateSettings,proto3,oneof"`
}

type Envelope_Ack struct {
	// Ordering acks (40+). Not application frames; consumed by the bridge.
	Ack *Ack `protobuf:"bytes,40,opt,name=ack,proto3,oneof"`
}

func (*Envelope_VqlStart) isEnvelope_Body() {}

func (*Envelope_VqlUserText) isEnvelope_Body() {}

func (*Envelope_VqlInterruption) isEnvelope_Body() {}

func (*Envelope_VqlInferenceFinalized) isEnvelope_Body() {}

func (*Envelope_VqlLlmStart) isEnvelope_Body() {}

func (*Envelope_VqlLlmText) isEnvelope_Body() {}

func (*Envelope_VqlLlmEnd) isEnvelope_Body() {}

func (*Envelope_VqlFcStarted) isEnvelope_Body() {}

func (*Envelope_VqlFcInProgress) isEnvelope_Body() {}

func (*Envelope_VqlFcResult) isEnvelope_Body() {}

func (*Envelope_VqlInteractionCompleted) isEnvelope_Body() {}

func (*Envelope_VqlUserIdle) isEnvelope_Body() {}

func (*Envelope_End) isEnvelope_Body() {}

func (*Envelope_Cancel) isEnvelope_Body() {}

func (*Envelope_Error) isEnvelope_Body() {}

func (*Envelope_RtviServerMessage) isEnvelope_Body() {}

func (*Envelope_SttUpdateSettings) isEnvelope_Body() {}

func (*Envelope_TtsUpdateSettings) isEnvelope_Body() {}

func (*Envelope_RtviClientMessage) isEnvelope_Body() {}

func (*Envelope_IdleUpdateSettings) isEnvelope_Body() {}

func (*Envelope_Ack) isEnvelope_Body() {}

// First frame on the wire. session_id and agent_id are named protocol fields;
// `payload` is opaque customer-defined init data, JSON-encoded.
//
// VqlStart also carries the pipecat StartFrame fields the agent's logical
// pipeline needs to bootstrap (sample rates, metrics flags). Tracing context
// is intentionally omitted — not portable across processes.
type VqlStart struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId   string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload   string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Inherited pipecat StartFrame fields.
	AudioInSampleRate     uint32 `protobuf:"varint,10,opt,name=audio_in_sample_rate,json=audioInSampleRate,proto3" json:"audio_in_sample_rate,omitempty"`
	AudioOutSampleRate    uint32 `protobuf:"varint,11,opt,name=audio_out_sample_rate,json=audioOutSampleRate,proto3" json:"audio_out_sample_rate,omitempty"`
	EnableMetrics         bool   `protobuf:"varint,12,opt,name=enable_metrics,json=enableMetrics,proto3" json:"enable_metrics,omitempty"`
	EnableTracing         bool   `protobuf:"varint,13,opt,name=enable_tracing,json=enableTracing,proto3" json:"enable_tracing,omitempty"`
	EnableUsageMetrics    bool   `protobuf:"varint,14,opt,name=enable_usage_metrics,json=enableUsageMetrics,proto3" json:"enable_usage_metrics,omitempty"`
	ReportOnlyInitialTtfb bool   `protobuf:"varint,15,opt,name=report_only_initial_ttfb,json=reportOnlyInitialTtfb,proto3" json:"report_only_initial_ttfb,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VqlStart) Reset() {
	*x = VqlStart{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlStart) ProtoMessage() {}

func (x *VqlStart) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlStart.ProtoReflect.Descriptor instead.
func (*VqlStart) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{1}
}

func (x *VqlStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VqlStart) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *VqlStart) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *VqlStart) GetAudioInSampleRate() uint32 {
	if x != nil {
		return x.AudioInSampleRate
	}
	return 0
}

func (x *VqlStart) GetAudioOutSampleRate() uint32 {
	if x != nil {
		return x.AudioOutSampleRate
	}
	return 0
}

func (x *VqlStart) GetEnableMetrics() bool {
	if x != nil {
		return x.EnableMetrics
	}
	return false
}

func (x *VqlStart) GetEnableTracing() bool {
	if x != nil {
		return x.EnableTracing
	}
	return false
}

func (x *VqlStart) GetEnableUsageMetrics() bool {
	if x != nil {
		return x.EnableUsageMetrics
	}
	return false
}

func (x *VqlStart) GetReportOnlyInitialTtfb() bool {
	if x != nil {
		return x.ReportOnlyInitialTtfb
	}
	return false
}

// Committed user stimulus for one interaction. interaction_id is Voice-minted,
// session-monotonic. Emitted downstream by UserContextAggregator.
type VqlUserText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlUserText) Reset() {
	*x = VqlUserText{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlUserText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlUserText) ProtoMessage() {}

func (x *VqlUserText) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlUserText.ProtoReflect.Descriptor instead.
func (*VqlUserText) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{2}
}

func (x *VqlUserText) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlUserText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Voice-opened idle interaction. Voice detected the user has been silent past
// the configured idle timeout and opened a fresh interaction so the Brain can
// re-engage ("still there?"). interaction_id is Voice-minted, same monotonic
// space as VqlUserText — the Brain responds through it and returns
// VqlInteractionCompleted exactly like a spoken turn. level counts consecutive
// idle escalations without intervening user speech (1 = first nudge); it resets
// when the user speaks. idle_ms is the silence elapsed when the interaction
// opened.
type VqlUserIdle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	IdleMs        uint32                 `protobuf:"varint,3,opt,name=idle_ms,json=idleMs,proto3" json:"idle_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlUserIdle) Reset() {
	*x = VqlUserIdle{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlUserIdle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlUserIdle) ProtoMessage() {}

func (x *VqlUserIdle) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlUserIdle.ProtoReflect.Descriptor instead.
func (*VqlUserIdle) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{3}
}

func (x *VqlUserIdle) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlUserIdle) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *VqlUserIdle) GetIdleMs() uint32 {
	if x != nil {
		return x.IdleMs
	}
	return 0
}

// Pure interruption signal — field-less. Maps to pipecat's native
// InterruptionFrame; correlation is carried by inference_id on the data frames,
// not here.
type VqlInterruption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlInterruption) Reset() {
	*x = VqlInterruption{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlInterruption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlInterruption) ProtoMessage() {}

func (x *VqlInterruption) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlInterruption.ProtoReflect.Descriptor instead.
func (*VqlInterruption) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{4}
}

// Per-inference finalize: the text the user actually heard for ONE inference
// (never a cross-inference concatenation). interaction_id + inference_id are the
// composite key.
type VqlInferenceFinalized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	HeardText     string                 `protobuf:"bytes,3,opt,name=heard_text,json=heardText,proto3" json:"heard_text,omitempty"`
	Interrupted   bool                   `protobuf:"varint,4,opt,name=interrupted,proto3" json:"interrupted,omitempty"`
	Reason        FinalizeReason         `protobuf:"varint,5,opt,name=reason,proto3,enum=voqalize.frames.FinalizeReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlInferenceFinalized) Reset() {
	*x = VqlInferenceFinalized{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlInferenceFinalized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlInferenceFinalized) ProtoMessage() {}

func (x *VqlInferenceFinalized) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlInferenceFinalized.ProtoReflect.Descriptor instead.
func (*VqlInferenceFinalized) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{5}
}

func (x *VqlInferenceFinalized) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlInferenceFinalized) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *VqlInferenceFinalized) GetHeardText() string {
	if x != nil {
		return x.HeardText
	}
	return ""
}

func (x *VqlInferenceFinalized) GetInterrupted() bool {
	if x != nil {
		return x.Interrupted
	}
	return false
}

func (x *VqlInferenceFinalized) GetReason() FinalizeReason {
	if x != nil {
		return x.Reason
	}
	return FinalizeReason_FINALIZE_REASON_UNSPECIFIED
}

type VqlLLMFullResponseStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlLLMFullResponseStart) Reset() {
	*x = VqlLLMFullResponseStart{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlLLMFullResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlLLMFullResponseStart) ProtoMessage() {}

func (x *VqlLLMFullResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlLLMFullResponseStart.ProtoReflect.Descriptor instead.
func (*VqlLLMFullResponseStart) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{6}
}

func (x *VqlLLMFullResponseStart) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlLLMFullResponseStart) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

type VqlLLMText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlLLMText) Reset() {
	*x = VqlLLMText{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlLLMText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlLLMText) ProtoMessage() {}

func (x *VqlLLMText) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlLLMText.ProtoReflect.Descriptor instead.
func (*VqlLLMText) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{7}
}

func (x *VqlLLMText) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlLLMText) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *VqlLLMText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type VqlLLMFullResponseEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlLLMFullResponseEnd) Reset() {
	*x = VqlLLMFullResponseEnd{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlLLMFullResponseEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlLLMFullResponseEnd) ProtoMessage() {}

func (x *VqlLLMFullResponseEnd) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlLLMFullResponseEnd.ProtoReflect.Descriptor instead.
func (*VqlLLMFullResponseEnd) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{8}
}

func (x *VqlLLMFullResponseEnd) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlLLMFullResponseEnd) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

type VqlFunctionCallsStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,4,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Arguments     string                 `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlFunctionCallsStarted) Reset() {
	*x = VqlFunctionCallsStarted{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlFunctionCallsStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlFunctionCallsStarted) ProtoMessage() {}

func (x *VqlFunctionCallsStarted) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlFunctionCallsStarted.ProtoReflect.Descriptor instead.
func (*VqlFunctionCallsStarted) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{9}
}

func (x *VqlFunctionCallsStarted) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlFunctionCallsStarted) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *VqlFunctionCallsStarted) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *VqlFunctionCallsStarted) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *VqlFunctionCallsStarted) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type VqlFunctionCallInProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,4,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Arguments     string                 `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlFunctionCallInProgress) Reset() {
	*x = VqlFunctionCallInProgress{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlFunctionCallInProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlFunctionCallInProgress) ProtoMessage() {}

func (x *VqlFunctionCallInProgress) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlFunctionCallInProgress.ProtoReflect.Descriptor instead.
func (*VqlFunctionCallInProgress) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{10}
}

func (x *VqlFunctionCallInProgress) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlFunctionCallInProgress) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *VqlFunctionCallInProgress) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *VqlFunctionCallInProgress) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *VqlFunctionCallInProgress) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type VqlFunctionCallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InferenceId   uint64                 `protobuf:"varint,2,opt,name=inference_id,json=inferenceId,proto3" json:"inference_id,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,4,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"` // JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlFunctionCallResult) Reset() {
	*x = VqlFunctionCallResult{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlFunctionCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlFunctionCallResult) ProtoMessage() {}

func (x *VqlFunctionCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlFunctionCallResult.ProtoReflect.Descriptor instead.
func (*VqlFunctionCallResult) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{11}
}

func (x *VqlFunctionCallResult) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

func (x *VqlFunctionCallResult) GetInferenceId() uint64 {
	if x != nil {
		return x.InferenceId
	}
	return 0
}

func (x *VqlFunctionCallResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *VqlFunctionCallResult) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *VqlFunctionCallResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Brain → Voice: the Brain is done responding to the whole interaction (emitted
// when on_interaction returns cleanly). Barge-in skips this — Voice finalizes the
// cut inference directly. Idempotent per interaction_id.
type VqlInteractionCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InteractionId uint64                 `protobuf:"varint,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VqlInteractionCompleted) Reset() {
	*x = VqlInteractionCompleted{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VqlInteractionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VqlInteractionCompleted) ProtoMessage() {}

func (x *VqlInteractionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VqlInteractionCompleted.ProtoReflect.Descriptor instead.
func (*VqlInteractionCompleted) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{12}
}

func (x *VqlInteractionCompleted) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

type End struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *End) Reset() {
	*x = End{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *End) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*End) ProtoMessage() {}

func (x *End) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use End.ProtoReflect.Descriptor instead.
func (*End) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{13}
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{14}
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Fatal         bool                   `protobuf:"varint,2,opt,name=fatal,proto3" json:"fatal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{15}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Error) GetFatal() bool {
	if x != nil {
		return x.Fatal
	}
	return false
}

// Carries pipecat's RTVIServerMessageFrame.data verbatim, JSON-encoded.
// Direction on the wire (byte prefix) is set by the sender's push_frame call;
// for browser-bound server messages the agent pushes UPSTREAM so pygato's
// RTVI processor (upstream of the cortex bridge) picks it up.
type RTVIServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTVIServerMessage) Reset() {
	*x = RTVIServerMessage{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTVIServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTVIServerMessage) ProtoMessage() {}

func (x *RTVIServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTVIServerMessage.ProtoReflect.Descriptor instead.
func (*RTVIServerMessage) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{16}
}

func (x *RTVIServerMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Carries pipecat's RTVIClientMessageFrame — a browser→Brain custom message
// (e.g. state_sync). pygato's RTVI processor emits it DOWNSTREAM into the cortex
// bridge, which forwards it to the customer agent; the SDK surfaces it as
// `on_client_message`. `data` is the message's `d` payload, JSON-encoded.
//
// EVERY client message is delivered to the Brain — Voice never interprets `type`
// and there is no respond:true/false flag. The Brain decides what to do: update
// its own state (and let a tool read it on demand), append it to history without
// running the model, or spend the stamped interaction_id on an inference right
// away. Most ids never drive an inference, and that is fine. Delivered
// fire-and-forget (no ack) so high-frequency ambient messages (e.g. state_sync)
// never block the ordered conversation lane.
type RTVIClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MsgId string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Data  string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded
	// Voice-minted session-monotonic stamp, in the same space as VqlUserText /
	// VqlUserIdle, letting the Brain spend this message's turn on an inference.
	//
	// ADDED LATER — 0/absent means "unstamped", i.e. the sender is an older pygato
	// that predates the stamp. Real ids start at 1, so 0 can never collide with a
	// live interaction. An unstamped message still reaches the Brain and still
	// updates its state; the Brain just cannot spend the id and must respond (if
	// it wants to) with an agent-initiated turn instead.
	InteractionId uint64 `protobuf:"varint,4,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTVIClientMessage) Reset() {
	*x = RTVIClientMessage{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTVIClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTVIClientMessage) ProtoMessage() {}

func (x *RTVIClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTVIClientMessage.ProtoReflect.Descriptor instead.
func (*RTVIClientMessage) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{17}
}

func (x *RTVIClientMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RTVIClientMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RTVIClientMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RTVIClientMessage) GetInteractionId() uint64 {
	if x != nil {
		return x.InteractionId
	}
	return 0
}

// Carries pipecat's STTUpdateSettingsFrame.settings (legacy dict path).
// Receiver reconstructs STTUpdateSettingsFrame(settings=<decoded>); pipecat's
// STT services convert dict → typed delta with a deprecation warning.
// Agent pushes UPSTREAM so it reaches pygato's STT (upstream of the bridge).
type STTUpdateSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      string                 `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"` // JSON-encoded dict
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STTUpdateSettings) Reset() {
	*x = STTUpdateSettings{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STTUpdateSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STTUpdateSettings) ProtoMessage() {}

func (x *STTUpdateSettings) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STTUpdateSettings.ProtoReflect.Descriptor instead.
func (*STTUpdateSettings) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{18}
}

func (x *STTUpdateSettings) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

// Carries pipecat's TTSUpdateSettingsFrame.settings (legacy dict path).
// Agent pushes DOWNSTREAM so it reaches pygato's TTS (downstream of the bridge).
type TTSUpdateSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      string                 `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"` // JSON-encoded dict
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSUpdateSettings) Reset() {
	*x = TTSUpdateSettings{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSUpdateSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSUpdateSettings) ProtoMessage() {}

func (x *TTSUpdateSettings) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSUpdateSettings.ProtoReflect.Descriptor instead.
func (*TTSUpdateSettings) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{19}
}

func (x *TTSUpdateSettings) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

// Brain → Voice: (re)configure idle detection mid-session — the idle half of
// the voice-protocol session.configure() DTO, mirroring STT/TTSUpdateSettings.
// settings is a JSON-encoded IdlePolicy (e.g. {"timeout_ms": 30000}); Voice
// applies it to its idle detector (pipecat UserIdleTimeoutUpdateFrame). A
// timeout of 0 disables idle detection.
type IdleUpdateSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      string                 `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"` // JSON-encoded IdlePolicy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdleUpdateSettings) Reset() {
	*x = IdleUpdateSettings{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdleUpdateSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdleUpdateSettings) ProtoMessage() {}

func (x *IdleUpdateSettings) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdleUpdateSettings.ProtoReflect.Descriptor instead.
func (*IdleUpdateSettings) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{20}
}

func (x *IdleUpdateSettings) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

// Sent by the agent SDK after the customer's `process_frame` returns for a
// data frame the bridge sent with an ack_id. Used by the bridge to gate
// `push_frame` of subsequent plumbing frames so that pipecat's strict in-order
// dispatch contract is preserved across the websocket round-trip.
//
// Acks are wire-level — they do not appear as pipecat Frames in either
// pipeline. ack_id is bridge-scoped; counter starts at 1 and is monotonic
// per bridge instance.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckId         uint64                 `protobuf:"varint,1,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_voqalize_frames_frames_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_voqalize_frames_frames_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_voqalize_frames_frames_proto_rawDescGZIP(), []int{21}
}

func (x *Ack) GetAckId() uint64 {
	if x != nil {
		return x.AckId
	}
	return 0
}

var File_voqalize_frames_frames_proto protoreflect.FileDescriptor

const file_voqalize_frames_frames_proto_rawDesc = "" +
	"\n" +
	"\x1cvoqalize/frames/frames.proto\x12\x0fvoqalize.frames\"\xca\f\n" +
	"\bEnvelope\x128\n" +
	"\tvql_start\x18\x01 \x01(\v2\x19.voqalize.frames.VqlStartH\x00R\bvqlStart\x12B\n" +
	"\rvql_user_text\x18\x02 \x01(\v2\x1c.voqalize.frames.VqlUserTextH\x00R\vvqlUserText\x12M\n" +
	"\x10vql_interruption\x18\x03 \x01(\v2 .voqalize.frames.VqlInterruptionH\x00R\x0fvqlInterruption\x12`\n" +
	"\x17vql_inference_finalized\x18\x04 \x01(\v2&.voqalize.frames.VqlInferenceFinalizedH\x00R\x15vqlInferenceFinalized\x12N\n" +
	"\rvql_llm_start\x18\x05 \x01(\v2(.voqalize.frames.VqlLLMFullResponseStartH\x00R\vvqlLlmStart\x12?\n" +
	"\fvql_llm_text\x18\x06 \x01(\v2\x1b.voqalize.frames.VqlLLMTextH\x00R\n" +
	"vqlLlmText\x12H\n" +
	"\vvql_llm_end\x18\a \x01(\v2&.voqalize.frames.VqlLLMFullResponseEndH\x00R\tvqlLlmEnd\x12P\n" +
	"\x0evql_fc_started\x18\b \x01(\v2(.voqalize.frames.VqlFunctionCallsStartedH\x00R\fvqlFcStarted\x12Y\n" +
	"\x12vql_fc_in_progress\x18\t \x01(\v2*.voqalize.frames.VqlFunctionCallInProgressH\x00R\x0fvqlFcInProgress\x12L\n" +
	"\rvql_fc_result\x18\n" +
	" \x01(\v2&.voqalize.frames.VqlFunctionCallResultH\x00R\vvqlFcResult\x12f\n" +
	"\x19vql_interaction_completed\x18\v \x01(\v2(.voqalize.frames.VqlInteractionCompletedH\x00R\x17vqlInteractionCompleted\x12B\n" +
	"\rvql_user_idle\x18\f \x01(\v2\x1c.voqalize.frames.VqlUserIdleH\x00R\vvqlUserIdle\x12(\n" +
	"\x03end\x18\x1f \x01(\v2\x14.voqalize.frames.EndH\x00R\x03end\x121\n" +
	"\x06cancel\x18  \x01(\v2\x17.voqalize.frames.CancelH\x00R\x06cancel\x12.\n" +
	"\x05error\x18! \x01(\v2\x16.voqalize.frames.ErrorH\x00R\x05error\x12T\n" +
	"\x13rtvi_server_message\x18\" \x01(\v2\".voqalize.frames.RTVIServerMessageH\x00R\x11rtviServerMessage\x12T\n" +
	"\x13stt_update_settings\x18# \x01(\v2\".voqalize.frames.STTUpdateSettingsH\x00R\x11sttUpdateSettings\x12T\n" +
	"\x13tts_update_settings\x18$ \x01(\v2\".voqalize.frames.TTSUpdateSettingsH\x00R\x11ttsUpdateSettings\x12T\n" +
	"\x13rtvi_client_message\x18% \x01(\v2\".voqalize.frames.RTVIClientMessageH\x00R\x11rtviClientMessage\x12W\n" +
	"\x14idle_update_settings\x18& \x01(\v2#.voqalize.frames.IdleUpdateSettingsH\x00R\x12idleUpdateSettings\x12(\n" +
	"\x03ack\x18( \x01(\v2\x14.voqalize.frames.AckH\x00R\x03ack\x12\x1d\n" +
	"\n" +
	"request_id\x182 \x01(\x04R\trequestIdB\x06\n" +
	"\x04body\"\xfb\x02\n" +
	"\bVqlStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12/\n" +
	"\x14audio_in_sample_rate\x18\n" +
	" \x01(\rR\x11audioInSampleRate\x121\n" +
	"\x15audio_out_sample_rate\x18\v \x01(\rR\x12audioOutSampleRate\x12%\n" +
	"\x0eenable_metrics\x18\f \x01(\bR\renableMetrics\x12%\n" +
	"\x0eenable_tracing\x18\r \x01(\bR\renableTracing\x120\n" +
	"\x14enable_usage_metrics\x18\x0e \x01(\bR\x12enableUsageMetrics\x127\n" +
	"\x18report_only_initial_ttfb\x18\x0f \x01(\bR\x15reportOnlyInitialTtfb\"H\n" +
	"\vVqlUserText\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"c\n" +
	"\vVqlUserIdle\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x17\n" +
	"\aidle_ms\x18\x03 \x01(\rR\x06idleMs\"\x11\n" +
	"\x0fVqlInterruption\"\xdb\x01\n" +
	"\x15VqlInferenceFinalized\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\x12\x1d\n" +
	"\n" +
	"heard_text\x18\x03 \x01(\tR\theardText\x12 \n" +
	"\vinterrupted\x18\x04 \x01(\bR\vinterrupted\x127\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x1f.voqalize.frames.FinalizeReasonR\x06reason\"c\n" +
	"\x17VqlLLMFullResponseStart\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\"j\n" +
	"\n" +
	"VqlLLMText\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"a\n" +
	"\x15VqlLLMFullResponseEnd\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\"\xc8\x01\n" +
	"\x17VqlFunctionCallsStarted\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12#\n" +
	"\rfunction_name\x18\x04 \x01(\tR\ffunctionName\x12\x1c\n" +
	"\targuments\x18\x05 \x01(\tR\targuments\"\xca\x01\n" +
	"\x19VqlFunctionCallInProgress\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12#\n" +
	"\rfunction_name\x18\x04 \x01(\tR\ffunctionName\x12\x1c\n" +
	"\targuments\x18\x05 \x01(\tR\targuments\"\xc0\x01\n" +
	"\x15VqlFunctionCallResult\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\x12!\n" +
	"\finference_id\x18\x02 \x01(\x04R\vinferenceId\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12#\n" +
	"\rfunction_name\x18\x04 \x01(\tR\ffunctionName\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\"@\n" +
	"\x17VqlInteractionCompleted\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\x04R\rinteractionId\"\x05\n" +
	"\x03End\" \n" +
	"\x06Cancel\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"3\n" +
	"\x05Error\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x14\n" +
	"\x05fatal\x18\x02 \x01(\bR\x05fatal\"'\n" +
	"\x11RTVIServerMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"y\n" +
	"\x11RTVIClientMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12%\n" +
	"\x0einteraction_id\x18\x04 \x01(\x04R\rinteractionId\"/\n" +
	"\x11STTUpdateSettings\x12\x1a\n" +
	"\bsettings\x18\x01 \x01(\tR\bsettings\"/\n" +
	"\x11TTSUpdateSettings\x12\x1a\n" +
	"\bsettings\x18\x01 \x01(\tR\bsettings\"0\n" +
	"\x12IdleUpdateSettings\x12\x1a\n" +
	"\bsettings\x18\x01 \x01(\tR\bsettings\"\x1c\n" +
	"\x03Ack\x12\x15\n" +
	"\x06ack_id\x18\x01 \x01(\x04R\x05ackId*s\n" +
	"\x0eFinalizeReason\x12\x1f\n" +
	"\x1bFINALIZE_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FINALIZE_REASON_COMPLETED\x10\x01\x12!\n" +
	"\x1dFINALIZE_REASON_USER_BARGE_IN\x10\x02B<Z:github.com/voqalize/voqalize/sdk/go/wire/framespb;framespbb\x06proto3"

var (
	file_voqalize_frames_frames_proto_rawDescOnce sync.Once
	file_voqalize_frames_frames_proto_rawDescData []byte
)

func file_voqalize_frames_frames_proto_rawDescGZIP() []byte {
	file_voqalize_frames_frames_proto_rawDescOnce.Do(func() {
		file_voqalize_frames_frames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voqalize_frames_frames_proto_rawDesc), len(file_voqalize_frames_frames_proto_rawDesc)))
	})
	return file_voqalize_frames_frames_proto_rawDescData
}

var file_voqalize_frames_frames_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_voqalize_frames_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_voqalize_frames_frames_proto_goTypes = []any{
	(FinalizeReason)(0),               // 0: voqalize.frames.FinalizeReason
	(*Envelope)(nil),                  // 1: voqalize.frames.Envelope
	(*VqlStart)(nil),                  // 2: voqalize.frames.VqlStart
	(*VqlUserText)(nil),               // 3: voqalize.frames.VqlUserText
	(*VqlUserIdle)(nil),               // 4: voqalize.frames.VqlUserIdle
	(*VqlInterruption)(nil),           // 5: voqalize.frames.VqlInterruption
	(*VqlInferenceFinalized)(nil),     // 6: voqalize.frames.VqlInferenceFinalized
	(*VqlLLMFullResponseStart)(nil),   // 7: voqalize.frames.VqlLLMFullResponseStart
	(*VqlLLMText)(nil),                // 8: voqalize.frames.VqlLLMText
	(*VqlLLMFullResponseEnd)(nil),     // 9: voqalize.frames.VqlLLMFullResponseEnd
	(*VqlFunctionCallsStarted)(nil),   // 10: voqalize.frames.VqlFunctionCallsStarted
	(*VqlFunctionCallInProgress)(nil), // 11: voqalize.frames.VqlFunctionCallInProgress
	(*VqlFunctionCallResult)(nil),     // 12: voqalize.frames.VqlFunctionCallResult
	(*VqlInteractionCompleted)(nil),   // 13: voqalize.frames.VqlInteractionCompleted
	(*End)(nil),                       // 14: voqalize.frames.End
	(*Cancel)(nil),                    // 15: voqalize.frames.Cancel
	(*Error)(nil),                     // 16: voqalize.frames.Error
	(*RTVIServerMessage)(nil),         // 17: voqalize.frames.RTVIServerMessage
	(*RTVIClientMessage)(nil),         // 18: voqalize.frames.RTVIClientMessage
	(*STTUpdateSettings)(nil),         // 19: voqalize.frames.STTUpdateSettings
	(*TTSUpdateSettings)(nil),         // 20: voqalize.frames.TTSUpdateSettings
	(*IdleUpdateSettings)(nil),        // 21: voqalize.frames.IdleUpdateSettings
	(*Ack)(nil),                       // 22: voqalize.frames.Ack
}
var file_voqalize_frames_frames_proto_depIdxs = []int32{
	2,  // 0: voqalize.frames.Envelope.vql_start:type_name -> voqalize.frames.VqlStart
	3,  // 1: voqalize.frames.Envelope.vql_user_text:type_name -> voqalize.frames.VqlUserText
	5,  // 2: voqalize.frames.Envelope.vql_interruption:type_name -> voqalize.frames.VqlInterruption
	6,  // 3: voqalize.frames.Envelope.vql_inference_finalized:type_name -> voqalize.frames.VqlInferenceFinalized
	7,  // 4: voqalize.frames.Envelope.vql_llm_start:type_name -> voqalize.frames.VqlLLMFullResponseStart
	8,  // 5: voqalize.frames.Envelope.vql_llm_text:type_name -> voqalize.frames.VqlLLMText
	9,  // 6: voqalize.frames.Envelope.vql_llm_end:type_name -> voqalize.frames.VqlLLMFullResponseEnd
	10, // 7: voqalize.frames.Envelope.vql_fc_started:type_name -> voqalize.frames.VqlFunctionCallsStarted
	11, // 8: voqalize.frames.Envelope.vql_fc_in_progress:type_name -> voqalize.frames.VqlFunctionCallInProgress
	12, // 9: voqalize.frames.Envelope.vql_fc_result:type_name -> voqalize.frames.VqlFunctionCallResult
	13, // 10: voqalize.frames.Envelope.vql_interaction_completed:type_name -> voqalize.frames.VqlInteractionCompleted
	4,  // 11: voqalize.frames.Envelope.vql_user_idle:type_name -> voqalize.frames.VqlUserIdle
	14, // 12: voqalize.frames.Envelope.end:type_name -> voqalize.frames.End
	15, // 13: voqalize.frames.Envelope.cancel:type_name -> voqalize.frames.Cancel
	16, // 14: voqalize.frames.Envelope.error:type_name -> voqalize.frames.Error
	17, // 15: voqalize.frames.Envelope.rtvi_server_message:type_name -> voqalize.frames.RTVIServerMessage
	19, // 16: voqalize.frames.Envelope.stt_update_settings:type_name -> voqalize.frames.STTUpdateSettings
	20, // 17: voqalize.frames.Envelope.tts_update_settings:type_name -> voqalize.frames.TTSUpdateSettings
	18, // 18: voqalize.frames.Envelope.rtvi_client_message:type_name -> voqalize.frames.RTVIClientMessage
	21, // 19: voqalize.frames.Envelope.idle_update_settings:type_name -> voqalize.frames.IdleUpdateSettings
	22, // 20: voqalize.frames.Envelope.ack:type_name -> voqalize.frames.Ack
	0,  // 21: voqalize.frames.VqlInferenceFinalized.reason:type_name -> voqalize.frames.FinalizeReason
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_voqalize_frames_frames_proto_init() }
func file_voqalize_frames_frames_proto_init() {
	if File_voqalize_frames_frames_proto != nil {
		return
	}
	file_voqalize_frames_frames_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_VqlStart)(nil),
		(*Envelope_VqlUserText)(nil),
		(*Envelope_VqlInterruption)(nil),
		(*Envelope_VqlInferenceFinalized)(nil),
		(*Envelope_VqlLlmStart)(nil),
		(*Envelope_VqlLlmText)(nil),
		(*Envelope_VqlLlmEnd)(nil),
		(*Envelope_VqlFcStarted)(nil),
		(*Envelope_VqlFcInProgress)(nil),
		(*Envelope_VqlFcResult)(nil),
		(*Envelope_VqlInteractionCompleted)(nil),
		(*Envelope_VqlUserIdle)(nil),
		(*Envelope_End)(nil),
		(*Envelope_Cancel)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_RtviServerMessage)(nil),
		(*Envelope_SttUpdateSettings)(nil),
		(*Envelope_TtsUpdateSettings)(nil),
		(*Envelope_RtviClientMessage)(nil),
		(*Envelope_IdleUpdateSettings)(nil),
		(*Envelope_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voqalize_frames_frames_proto_rawDesc), len(file_voqalize_frames_frames_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_voqalize_frames_frames_proto_goTypes,
		DependencyIndexes: file_voqalize_frames_frames_proto_depIdxs,
		EnumInfos:         file_voqalize_frames_frames_proto_enumTypes,
		MessageInfos:      file_voqalize_frames_frames_proto_msgTypes,
	}.Build()
	File_voqalize_frames_frames_proto = out.File
	file_voqalize_frames_frames_proto_goTypes = nil
	file_voqalize_frames_frames_proto_depIdxs = nil
}
